import React, { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Pane, Heading } from 'evergreen-ui';
import ProjectService from '../services/projects';
import { IProject } from '../services/projects/interfaces';
import Layout from '../components/layout';
import ProjectCard from '../components/ProjectCard';

const Home: NextPage = () => {
  const [projects, setProjects] = useState<IProject[]>([]);

  useEffect(() => {
    const fetchActiveProjects = async () => {
      try {
        const data = await ProjectService.getAllActiveProjects();
        setProjects(data);
      } catch (error) {
        console.log(error);
      }
    };

    fetchActiveProjects();
  }, []);

  return (
    <Layout>
      <Head>
        <title>Vietnam Giving | Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vietnam.svg" />
      </Head>

      <Pane
        display="flex"
        alignItems="center"
        justifyContent="center"
        flexDirection="column">
        <Heading size={900}>Explore</Heading>

        {projects.map((project) => (
          <ProjectCard key="project.title" project={project} />
        ))}
      </Pane>
    </Layout>
  );
};

export default Home;
