import type { NextPage } from 'next';
import Head from 'next/head';
import { Pane, Heading } from 'evergreen-ui';
import Layout from '../components/Layout';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Vietnam Giving | Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Pane display="flex" alignItems="center" justifyContent="center">
        <Heading size={900}>Explore</Heading>
      </Pane>
    </Layout>
  );
};

export default Home;
